### ISSUE TITLE
add compatible with system.js and package.son with Typing compilation

### ISSUE THREAD

**Issue by sireneweb** [atais/ng2-eonasdan-datetimepicker#1]
Hi,
actually when i try to use ng2-eonasdan-datetimepicker with system.js and package.son config files, i get an error with visual studio
```
"devDependencies": {
    "browser-sync": "^2.12.10",
    "concurrently": "^2.2.0",
    "jasmine-core": "2.5.2",
    "jasmine-node": "^1.14.5",
    "jshint": "^2.9.2",
    "lite-server": "^2.2.0",
    "live-server": "^1.0.0",
    "ng2-eonasdan-datetimepicker": "0.0.2", <----
    "typescript": "^2.0.2", <----
    "typings": "^1.3.2" <----
  }
```

i geth these errors : 

```
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Build :Interface 'JQueryDeferred<T>' cannot simultaneously extend types 'JQueryPromise<T>' and 'JQueryGenericPromise<T>'.	
C:\myapp\Typescripts\jquery.d.ts	428	
```

```
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Build :Interface 'JQueryEventObject' cannot simultaneously extend types 'BaseJQueryEventObject' and 'JQueryPopStateEventObject'.	
C:\myapp\Typescripts\jquery.d.ts	574	
```

```
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Build :Duplicate identifier 'export='.	Upsign Digital Client	C:\myapp\Typescripts\jquery.d.ts	3905	
```

in my folder typescripts, i have all ready jquery.d.ts and in my nodes_modules, i have 

![image](https://cloud.githubusercontent.com/assets/1773161/20774017/c2a59aea-b754-11e6-90b7-2bb23661c16b.png)

How can i solve this ?

**Comment by sireneweb** [comment]
my jquery.dts 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts

**Comment by atais** [comment]
I am currently using it in an application with Webpack.
I am learning system.js as we speak so I could provide some plunker example.

**Comment by sireneweb** [comment]
i have a jquery 3 in my node_modules, maybe the bug comes from here, but i don't know

**Comment by atais** [comment]
I think it could, because `eonasdan-datetimepicker` does not work with jQuery 3 and you might have two versions of jQuery in your application. Make sure to only use v2 and that no other plugin uses v3.
