### ISSUE TITLE
Support for Angular 4?

### ISSUE THREAD

**Issue by hirwandzahir** [atais/ng2-eonasdan-datetimepicker#15]
Hi, is it possible to add this plugin to a angular4 project? I have tried to add and it will install all angular2 dependencies into my angular4 project which will cause a conflict once I ran it. 

Im adding this plugin via yarn.

**Comment by atais** [comment]
Could you print the dependency tree, why angular 4 is miss matched with required angular dependencies of: 

```
"@angular/common": "^2.0.0",
"@angular/compiler": "^2.0.0",
"@angular/core": "^2.0.0",
"@angular/platform-browser": "^2.0.0",
"@angular/platform-browser-dynamic": "^2.0.0",
```

**Comment by hirwandzahir** [comment]
> "@angular/common@^4.1.3":
>   version "4.1.3"
>   resolved "https://registry.yarnpkg.com/@angular/common/-/common-4.1.3.tgz#e7c4791e32131cf74c239428c2a67daab2eef017"
> 
> "@angular/compiler-cli@^4.1.3":
>   version "4.1.3"
>   resolved "https://registry.yarnpkg.com/@angular/compiler-cli/-/compiler-cli-4.1.3.tgz#c2362ffdf65756471481f839fab675bcac213f96"
>   dependencies:
>     "@angular/tsc-wrapped" "4.1.3"
>     minimist "^1.2.0"
>     reflect-metadata "^0.1.2"
> 
> "@angular/compiler@^4.1.3":
>   version "4.1.3"
>   resolved "https://registry.yarnpkg.com/@angular/compiler/-/compiler-4.1.3.tgz#d2dd30853b0cf4a54758b4a314632c231f9c94c3"
> 
> "@angular/core@^4.1.3":
>   version "4.1.3"
>   resolved "https://registry.yarnpkg.com/@angular/core/-/core-4.1.3.tgz#285498eb86ab7d0b6f982f8f9f487ef610013b35"

above is my yarn.lock file before I add the plugin.

For your information, currently my project is using angular 4 as core. So, when i added this ng2 plugin, it will also install angular 2 for all of the above packages (so I have 2 @angular/code, @angular/common, etc - but in angular2 version). Therefore, when I tried to use the component is my project the error message is this:

`Uncaught Error: Unexpected value 'A2Edatetimepicker' imported by the module 'OrderModule'. Please add a @NgModule annotation.`

**Comment by Sarmak5** [comment]
Hi. I have the same issue on angular 4.2.6.
I use webpack:
`"ng2-eonasdan-datetimepicker": "0.0.7"`
I've added import to my app.module.ts:
```
import {A2Edatetimepicker} from 'ng2-eonasdan-datetimepicker';
@NgModule({
  imports: [
....
    A2Edatetimepicker
  ],
```
and I use as 
` <div class="input-group">
                      <input class="form-control"
                             a2e-datetimepicker
                             [date]="dateTo"
                             [options]="a2eOptions"
                             (onChange)="dateToChange($event)"
                             (onClick)="dateClick()"/>
                      <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>`
but I've got an error during compiling: 
ERROR in A2Edatetimepicker is not an NgModule

**Comment by atais** [comment]
I would really like to prepare a system js, webpack and angular 4 demo versions if possible, and adjust the library to the requirements. 

However as said before I do not work with front-end anymore and I am focused on other projects.
I am still actively supporting the library and I can merge all the necessary changes presented by PRs but most likely I will not update it on my own in the nearest future

**Comment by atais** [comment]
can we close it?

**Comment by ssnake** [comment]
Even with 0.0.8 I have still issue on Angular 4
```
ERROR in A2Edatetimepicker is not an NgModule
```

**Comment by atais** [comment]
This error is not related to lack of support for Angular 4. But to be honest I do not longer know if it is because you import the module in the wrong way or it is an error for everyone.

**Comment by nigelpasco** [comment]
Same error for myselfas for ssnake. Clean install using instructions provided with angular 4.

    npm install "ng2-eonasdan-datetimepicker": "0.0.8"

    import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MdSelectModule } from '@angular/material';
import { A2Edatetimepicker } from 'ng2-eonasdan-datetimepicker';

import { NavbarComponent } from './navbar.component';

@NgModule({
    imports: [
      RouterModule,
      CommonModule,
      FormsModule, ReactiveFormsModule,
      MdSelectModule,
      A2Edatetimepicker
    ],
    declarations: [ NavbarComponent ],
    exports: [ NavbarComponent ]
})

export class NavbarModule {}

**Comment by martincarstens** [comment]
I had the same error and switched to using the directive instead of the module.

From

```
import { A2Edatetimepicker } from 'ng2-eonasdan-datetimepicker';

import 'eonasdan-bootstrap-datetimepicker';

@NgModule({
    imports: [ A2Edatetimepicker ],
    ...
})
```

To

```
import { DateTimePickerDirective } from 'ng2-eonasdan-datetimepicker/dist/datetimepicker.directive';

import 'eonasdan-bootstrap-datetimepicker';

@NgModule({
    declarations: [ DateTimePickerDirective ],
    ...
})
```

**Comment by jeet1995** [comment]
So did it work? @martincarstens
