### ISSUE TITLE
date() parameter must be one of [null, string, moment or Date]

### ISSUE THREAD

**Issue by egnashko** [atais/ng2-eonasdan-datetimepicker#17]
Hi, have a problem, everything ok but only one error don't give me to render my page, help please, have this error: 
```date() parameter must be one of [null, string, moment or Date]```
Also what i done look below
main.ts
```import 'eonasdan-bootstrap-datetimepicker';```
app.module.ts (used to use directive because have mistake with ngModule)
```
import { DateTimePickerDirective } from 'ng2-eonasdan-datetimepicker/dist/datetimepicker.directive';
import { MomentModule } from 'angular2-moment/moment.module';
```
my filter.ts (used to import '* as moment' because only 'moment' doesn't work)
```
import * as moment from 'moment';
...
export class myClassComponent {
    date: moment.Moment;
}
```
my template
```
<div class="input-group">
        <input class="form-control"
               type="text"
               placeholder="From"
               [(ngModel)]="filter.from"
               a2e-datetimepicker
               [date]="date"
        />
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
```

**Comment by atais** [comment]
I think the error is pretty obvious...

**Comment by lgellert** [comment]
I'm getting this error in the demo (https://embed.plnkr.co/vnU3TedIRqOFGXWRbXt0/) if I clear the first input of all text then switch to the next field. If a user clears the box it should bounce back to the previous state like it does if you enter an invalid date.

**Comment by lgellert** [comment]
@egnashko you need to instantiate the date field in your constructor `this.date = moment();`
