### ISSUE TITLE
Plunker Demo

### ISSUE THREAD

**Issue by sireneweb** [atais/ng2-eonasdan-datetimepicker#2]
It would be great if you can provide demo on plunker, thanks :)

**Comment by atais** [comment]
I know I am working on it :-)

**Comment by atais** [comment]
I have managed to create a simple demo.
I would really appreciate some help with it, but for now it is OK.

http://plnkr.co/edit/bUVVQu

**Comment by sireneweb** [comment]
Great news ! How i can help you ?

**Comment by atais** [comment]
@sireneweb if you know how to fix the issues I have mentioned in other post:

-  moment library can not be used in app.ts
-  datetimepicker dirty import is required for library to be imported

it would be most helpful 👍
