### ISSUE TITLE
Form/NgModel Support

### ISSUE THREAD

**Issue by lommez** [atais/ng2-eonasdan-datetimepicker#25]
When using something like this:

```
<form #form="ngForm" novalidate>
  <input a2e-datetimepicker [date]="startDate" [(ngMode)]="startDate" name="startDate" [options]="a2eOptions" (onChange)="dateStartChange($event)" required/>
</form>
```

The ngModel will conflict with the date property and shows non formatted date.

Anyone have an example of how to make it work with a form and ngmodel directive in angular?

**Comment by anuraagbitcot** [comment]
I listen to (onChange) emitter and assign the value of it to my ngModel in component.ts file. This was I can display date in a particular format and send back to my server in the format needed. 

Note: onnChange's `$event` gives `moment` object.

**Comment by atais** [comment]
So now as of `0.1.0` is this ticket still valid?

**Comment by fetrarij** [comment]
The `0.1.0` is  for form/ngModel . You can now use `ngModel` and `ngModelChange`instead of `date` and `onChange`
