### ISSUE TITLE
How to dynamically restrict date range when using 2 date pickers

### ISSUE THREAD

**Issue by albertStaalburger** [atais/ng2-eonasdan-datetimepicker#28]
With the `eonasdan-datetimepicker` you could update the `max` and `min` of a date picker by simply doing this:
```
.on("dp.change", function (e) {
    if (e.date) {
        $('#returnDatePicker').data("DateTimePicker").minDate(e.date.add(1, 'days'));
    }
});
```

With angular, I have tried both the jQuery above, which causes all kinds of madness as well as adding a `setMin()` method to the date picker options object.

Alas, none of those work.

Is this something that can be done?
If so, am I missing something?

**Comment by albertStaalburger** [comment]
Here is a simple plunker of what i have tried:
[https://plnkr.co/edit/9ZrYdxJIGkX5MvWlU079?p=preview](url)

**Comment by fetrarij** [comment]
@albertStaalburger  This is so easy with the new release 
https://embed.plnkr.co/5RsdBGbpz77sx5wPRGCy/
