### ISSUE TITLE
Porting Angular 1 demos 

### ISSUE THREAD

**Issue by atais** [atais/ng2-eonasdan-datetimepicker#3]
There is Angular 1 version of this library: https://github.com/atais/angular-eonasdan-datetimepicker
At the moment there are 4 examples for the Angular 1:

* Simple example, with one datetimepicker: http://plnkr.co/n8L8UZ
* Example with two, linked datetimepickers: http://plnkr.co/ZSjN8f
* Validation example: http://plnkr.co/NmFt43
* From/To validation example: http://plnkr.co/ZeKX7z

----
I am not sure how validation would work with Angular 2 - it is a place for discussion. Anyway it would be nice to have the examples ported to Angular 2.

Angular 2 examples:
- [x] Simple example, with one datetimepicker: https://embed.plnkr.co/vnU3TedIRqOFGXWRbXt0/
- [ ] Example with two, linked datetimepickers: 
- [ ] Validation example: 
- [ ] From/To validation example: 

I have created a simple plunker demo, but it is not done "properly" and not all the functions work. That is why it is incomplete.
**Fix list:**
- [x] moment library can not be used in app.ts 
- [x] datetimepicker dirty import is required for library to be imported

At the moment I do not know how to fix the above. 

Probably during creating new demos some bugs/ missing features will be found, that is why it is important to create them.
Thanks for help.

**Comment by sireneweb** [comment]
Sorry, the examples you provide is for Angular 1 or Angular 2?

**Comment by sireneweb** [comment]
i have found a great description about problem with Id in Angular2 

http://papajuras.com/index.php/2016/03/27/jquery-and-angular2/

**Comment by atais** [comment]
@sireneweb the link might be helpful, thanks.
I have also clarified the post. 
I had created an eonasdan-datetimepicker wrapper for Angular 1 and it is working quite well now. I want to adapt all the features to Angular 2 version so it could meet different requirements.
