### ISSUE TITLE
Open datepicker only on input click when using input-group

### ISSUE THREAD

**Issue by ikramcheb** [atais/ng2-eonasdan-datetimepicker#37]
Hi, I want to use datetimepicker input in an input-group but I want to open the calendar on input click 
 and prevent openning it on button click, because I will use the button for a different purpose . 

For example:

               <div class="input-group  pull-right">
                        <input type="text" class="form-control card-search" a2e-datetimepicker placeholder="{{'entity.common.to'|translate}}" name="to"
                            (onChange)="dateFilterChange($event,'to')" [date]="date" [options]="a2eOptions" #toInput />
                        <span class="input-group-addon" (click)="loadAll()">
                            <i class="fa fa-search"></i>
                        </span>
                   </div>

**Comment by fetrarij** [comment]
Hello, 

> but I want to open the calendar on input click

you can open the calendar on input click by using the option: allowInputToggle

> prevent openning it on button click, because I will use the button for a different purpose .

I don't think it's possible.  The [bootstrap datetimepicker](http://eonasdan.github.io/bootstrap-datetimepicker/) use this input-group-icon as main element to display the calendar. If we remove the input-group-icon, the calendar will throw an error.

**Comment by ikramcheb** [comment]
Ok thanks
