### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by atais** [atais/ng2-eonasdan-datetimepicker#39]
I think one of the last steps in this project is to implement some tests :-)

@fetrarij I do not know if you would have any spare time to implement them.
I could only suggest, that they could look like those that I have made for Angular 1 version of this project: https://github.com/atais/angular-eonasdan-datetimepicker

IMO you could use the "examples" projects for this purpose. Provide to them the source code and tests would be run on them with protractor or something?

I believe that it would greatly complete this code and allow for future changes with back compatibility. 
Locking versions in npm might be a good idea then.

**Comment by fetrarij** [comment]
@atais I've done it in development branch. What do you think?

**Comment by atais** [comment]
could you make a PR from dev to master, please?

**Comment by fetrarij** [comment]
done

**Comment by atais** [comment]
Excellent.
