### ISSUE TITLE
Share code between examples

### ISSUE THREAD

**Issue by atais** [atais/ng2-eonasdan-datetimepicker#40]
My mistake, 
but I think most of the code for both examples is shared. 

I think the easiest approach would be to remove duplicates and link the files where necessary.
It will be much easier to adapt the examples in future.

**Comment by fetrarij** [comment]
@atais I've done it in development branch. What do you think?

**Comment by atais** [comment]
Excellent work @fetrarij . I must say, without you this project would never be what it is now. 
Thanks so much for your contribution.

Also. I have now checked - please add your details to `package.json` in `contributors` section!

Should be something like:
```
  "contributors": [
    {
      "name": "xxx",
      "email": "if you like..."
    }
  ],
```
