### ISSUE TITLE
auto update ghpage

### ISSUE THREAD

**Issue by fetrarij** [atais/ng2-eonasdan-datetimepicker#43]
@atais Could you take a look on [ngh](https://www.npmjs.com/package/angular-cli-ghpages) .
It will auto update the gh-pages with the script built from `ng build`.
All we need to do is adding ngh, configure a github access for deploying (token will work), and add the command in travis ci..If you want.

**Comment by atais** [comment]
Good idea!
I can send you the token via email, what do you think?

**Comment by fetrarij** [comment]
You can already add it in travis environment variables settings: https://travis-ci.org/atais/ng2-eonasdan-datetimepicker/settings like `GH_TOKEN` , and I will do the rest

**Comment by atais** [comment]
I added the `GH_TOKEN` with `repo` scope, this should work right?

**Comment by fetrarij** [comment]
this should be good, thank you!
