### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by jsutStacy** [atais/ng2-eonasdan-datetimepicker#46]
CSS is broken. How to fix it?

![screen shot 2018-05-02 at 16 27 02](https://user-images.githubusercontent.com/6001676/39525808-bd8f0316-4e25-11e8-95f5-8f00021429dc.png)

angular-cli.json:

 "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css"

      ],
      "scripts": ["../node_modules/jquery/dist/jquery.min.js",
      "../node_modules/tether/dist/js/tether.min.js",
      "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/moment/moment.js",
        "../node_modules/moment/min/moment.min.js",
        "../node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js"
      ],

vendors.ts:

// css files
import 'bootstrap/dist/css/bootstrap.min.css';
import 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css';
// js files
import * as $ from 'jquery';
window['jQuery'] = window['$'] = $;
import 'bootstrap/dist/js/bootstrap.min.js';
import 'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js';
import * as moment from 'moment';

**Comment by fetrarij** [comment]
hello @jsutStacy ,

check our [webpack.config.json](https://github.com/atais/ng2-eonasdan-datetimepicker/blob/master/webpack/config/webpack.common.js) , you may need to add a `style-loader` for css test:

```
     {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap' })
      }, 
```

**Comment by jsutStacy** [comment]
This meant that I tried both angular-cli and webpack.
Anyway, when trying your advice I got the error:

ERROR in ./~/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
Module build failed: ReferenceError: window is not defined
ERROR in ./~/bootstrap/dist/css/bootstrap.min.css
Module build failed: ReferenceError: window is not defined

**Comment by jsutStacy** [comment]
yes,

    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^2.1.2",

**Comment by fetrarij** [comment]
how is your webpack.config.json?

**Comment by jsutStacy** [comment]
it has only these lines:

externals: {
  jquery: 'jQuery'
}

**Comment by fetrarij** [comment]
@jsutStacy in webpack.config.js , line 59, from the file you sent from the other topic, you should replace the line with the new one I said above.

**Comment by fetrarij** [comment]
I'm closing this issue since you doesn't give some news.
