### ISSUE TITLE
Input doesn't change its state to untouched on Form Reset

### ISSUE THREAD

**Issue by sivaRamsk88** [atais/ng2-eonasdan-datetimepicker#49]
Hi @fetrarij ,

I am using a2e-datetimepicker for reactive form input.

Form reset doesn't effect the input state. Input still in **touched**. Expected state of input is **untouched**

Please fix this.

**Comment by fetrarij** [comment]
Hello @sivaRamsk88 ,

Thanks for reporting.

**Comment by sivaRamsk88** [comment]
Still the issue persist. Please fix and close the issue. @fetrarij
