### ISSUE TITLE
Error: BrowserModule has already been loaded

### ISSUE THREAD

**Issue by dpinheiro** [atais/ng2-eonasdan-datetimepicker#5]
Hi

Was trying to use this module but faced this problem `Error: BrowserModule has already been loaded`

I was checking and your module is indeed importing the BrowserModule, it shouldn't do that https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-browser-vs-common-module

**Comment by atais** [comment]
Hi.

I would be really glad to help but unfortunately, I do not use Angular 2 anymore at all.

If you would like to contribute to this repository or fork it and maintain another version on your own, you are most welcome.

**Comment by dtopaloglou** [comment]
@dpinheiro I have the same issue also.

**Comment by suresh2018** [comment]
i have the same issue also

**Comment by fetrarij** [comment]
This is already fixed with the lastest version. The lib is now importing CommonModule instead of BrowserModule so it should be fine.
