### ISSUE TITLE
Unable to disable input in FormGroup

### ISSUE THREAD

**Issue by vjbhaskar93** [atais/ng2-eonasdan-datetimepicker#51]
Hi @fetrarij ,

`formGroupName.get('formControlName').disable();` is not working when the datepicker is used. 

Please fix this.

**Comment by fetrarij** [comment]
hello @vjbhaskar93 ,v0.1.3 is up.

Thanks

**Comment by vjbhaskar93** [comment]
Yay! It's working now. Thanks for the support @fetrarij
