### ISSUE TITLE
? How to build ?

### ISSUE THREAD

**Issue by JoelParke** [atais/ng2-eonasdan-datetimepicker#54]
I am attempting to remove a medium level vulnerability coming from bootstrap.  I have already built a version of eonasdan-datetimepicker with upgraded packages.  In attempting to build ng2-eonasdan-datetimepicker, I am running into a 'yarn install' problem.  
So clearly I don't quite understand enough.  
How to build this package locally?

What I am seeing after cloning the project and running 'yarn' is:
    
    rimraf dist && ngc

    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasmine/index.d.ts:14:18: Cannot redeclare block-scoped variable 'describe'.
    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasmine/index.d.ts:16:18: Cannot redeclare block-scoped variable 'xdescribe'.
    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasmine/index.d.ts:25:18: Cannot redeclare block-scoped variable 'it'.
    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasmine/index.d.ts:35:18: Cannot redeclare block-scoped variable 'xit'.
    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasminewd2/index.d.ts:9:18: Cannot redeclare block-scoped variable 'it'.
    Error at /home/joel/workspace/Tracker3/ng2-eonasdan-datetimepicker/node_modules/@types/jasminewd2/index.d.ts:11:18: Cannot redeclare block-scoped variable 'xit'.
    Error at /home/joel/workspace/Tracker3/node_modules/@types/mocha/index.d.ts:41:15: Cannot redeclare block-scoped variable 'describe'.
    Error at /home/joel/workspace/Tracker3/node_modules/@types/mocha/index.d.ts:42:15: Cannot redeclare block-scoped variable 'xdescribe'.
    Error at /home/joel/workspace/Tracker3/node_modules/@types/mocha/index.d.ts:47:15: Cannot redeclare block-scoped variable 'it'.
    Error at /home/joel/workspace/Tracker3/node_modules/@types/mocha/index.d.ts:48:15: Cannot redeclare block-scoped variable 'xit'.
    Error at /home/joel/workspace/Tracker3/node_modules/@types/passport/index.d.ts:15:13: Subsequent property declarations must have the same type.  Property 'user' must be of type 'any', but here has type 'User'.

**Comment by fetrarij** [comment]
Try to put it in a directory where there are no node_modules .

The error says there are node_modules in your Tracker3 directory which redeclare some variable in the new node_modules you installed after yarn install.

**Comment by JoelParke** [comment]
Thanks.  There was nothing in this directory.  But when I did a git clone https://github.com/atais/ng2-eonasdan-datetimepicker.git into a new directory, then yarn did the build as expect.  Sorry for the confusion.
