### ISSUE TITLE
Support for Angular 6

### ISSUE THREAD

**Issue by benjaminrlawrence** [atais/ng2-eonasdan-datetimepicker#56]
I'm using this in a project that is updating from Angular 2 to Angular 6 (I'm well aware that this is a huge jump). Will there be support for Angular 6 for this datetimepicker? If so, do you know what the timeframe for that is? If you're not doing this update anytime soon, would you be open to a pull request to update the code?

**Comment by fetrarij** [comment]
Hello. I am on holidays now, I will take a time for it.

**Comment by fetrarij** [comment]
helo @benjaminrlawrence, the plugin should work with angular 6. What issue do you have?

**Comment by benjaminrlawrence** [comment]
Hi @fetrarij, we were able to get it to work in our project, and the need for a fix was probably project-specific. We had to manually import a script, and then everything worked fine. Thanks for checking though. I'll close this.
