### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by atais** [atais/ng2-eonasdan-datetimepicker#6]
Unfortunately, I do not work with Angular 2 anymore and I am not able to develop & maintain this repository.

If one would like to become a contributor please contact me on email.

**Comment by souravmondal93** [comment]
@atais I don't know how much time I will be able to provide after my regular work, but I would like to maintain this repository.

**Comment by atais** [comment]
@souravmondal93 contact me on email for details

**Comment by atais** [comment]
@fetrarij is officially a maintainer :-)
For now, we can close this issue.
