### ISSUE TITLE
error in import datetimepicker from eonasdan-bootstrap-datetimepicker

### ISSUE THREAD

**Issue by anksuthar** [atais/ng2-eonasdan-datetimepicker#7]
It is not  run directly by same as code in new ng 2 app which is build by CLI

We need to give full path 

like

import { A2Edatetimepicker } from 'ng2-eonasdan-datetimepicker/src/datetimepicker.module';
import { DateTimePickerDirective } from 'ng2-eonasdan-datetimepicker/src/datetimepicker.directive';

When adding 
import datetimepicker from 'eonasdan-bootstrap-datetimepicker';

it gives error 

Error in import datetimepicker from 'eonasdan-bootstrap-datetimepicker';

So how we can import in our application 

We have not file system.js and other directly app.module.ts

![image](https://cloud.githubusercontent.com/assets/14817101/23660539/c7525b84-036f-11e7-994d-93c34b16a3c3.png)

![image](https://cloud.githubusercontent.com/assets/14817101/23660544/ce3e7658-036f-11e7-8481-d82fc2f40a6e.png)

**Comment by atais** [comment]
I think it is fixed with #27 and #31
